version: '2.1'

services:
  compositetestserver:
    build: ../../CompositeTestServer/
    environment:
      NODE_ENV: production
    ports:
      - 3100:3100
    depends_on:  
      - composite-test-db
  composite-test-db:
    image: mongo
    ports:
     - 27017:27017
  mongo-seed:
    build: ../../scripts/
    depends_on:
      - composite-test-db
  ##web-view:
    ##build: ../../CompositeTestWebView/
    ##ports:
     ## - 8080:80 
